### ISSUE TITLE
Task complexity display bug?

### ISSUE THREAD

**Issue by kolayne** [CoffeBee/MathBattle#39]
Here there are two screenshots of what I currently see at http://ab.math.silaeder.ru. Looks like it's a bug, isn't it?

![main_002](https://user-images.githubusercontent.com/23319866/97813498-b825ef80-1c99-11eb-87d1-e41c9648747c.png)
![main_003](https://user-images.githubusercontent.com/23319866/97813500-b9efb300-1c99-11eb-9ab9-35ff305960a9.png)

**Comment by CoffeBee** [comment]
No it's. On first shot you see difficulty of theme, and on second difficulty of exact task in exact theme

**Comment by kolayne** [comment]
Then is it a complexity calculation bug? Or is it expected that the complexity of a ~~theme~~ topic, containing the only "easy" task should be "middle"?

**Comment by justUlik** [comment]
There is no error in calculating the complexity. The task complexity is set manually by the task author, not programmatically
