### ISSUE TITLE
Incorrect number of solved tasks in a topic

### ISSUE THREAD

**Issue by kolayne** [CoffeBee/MathBattle#50]
http://ab.math.silaeder.ru/themes/theme/%D0%94%D0%97.%20%D0%93%D0%B5%D0%BE%D0%BC%D0%B5%D1%82%D1%80%D0%B8%D1%8F.%20%D0%BD%D0%B0%2016.11.2020/: seems like SeninGe should have 1 in the "Solved" column
![image](https://user-images.githubusercontent.com/23319866/99196151-90578100-279b-11eb-8a55-325e73f64457.png)

**Comment by CoffeBee** [comment]
Fix with commit 6b4432ae95201140654c09fdc7584a5f6adf7844

**Comment by kolayne** [comment]
No, it's not. Check out the URL from my first comment

**Comment by CoffeBee** [comment]
It's fix in master, but not deployed.
